<?php

namespace AppBundle\Repository;

/**
 * ColonyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColonyRepository extends \Doctrine\ORM\EntityRepository
{
}
