<?php

namespace AppBundle\Repository;

/**
 * PinExtractorDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PinExtractorDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
