<?php

namespace AppBundle\Repository;

/**
 * PinRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PinRouteRepository extends \Doctrine\ORM\EntityRepository
{
}
