<?php

namespace AppBundle\Repository;

/**
 * PinRouteWaypointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PinRouteWaypointRepository extends \Doctrine\ORM\EntityRepository
{
}
