<?php

namespace AppBundle\Repository;

/**
 * ToonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToonRepository extends \Doctrine\ORM\EntityRepository
{
}
