<?php

namespace sarelvdwalt\EVESDEBundle\Repository;

/**
 * invUniqueNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class invUniqueNameRepository extends \Doctrine\ORM\EntityRepository
{
}
